version: '2.1'

services:
  user:
    build:
      context: .
      dockerfile: Dockerfile.user
    image: mattipaksula/bause:user
  root:
    build:
      context: .
      dockerfile: Dockerfile.root
    image: mattipaksula/bause:root
